### PR TITLE
Add pheb2014939ctu

### PR DESCRIPTION
**Pull request by pheb2014939ctu**

### CODE REVIEW

**Comment by MrAshwin2142** [comment]
All the images look good, but I don't see any code in your PR to change them at fixed time intervals

**Comment by JohnPatrickAncajas** [comment]
I can work at adding that function tomorrow if he wouldn't/can't do it, if that's okay.

**Comment by MrAshwin2142** [comment]
sure @JohnPatrickAncajas

**Comment by pheb2014939ctu** [comment]
> All the images look good, but I don't see any code in your PR to change them at fixed time intervals

I'm about to submit the Pull Request for this task now. @ @MrAshwin2142

**Pull request merged**
